version: '3'

services:
  app:
    build: .
    ports:
      - "9000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always